internalName: nno

locales:
  en:
    name: &bundleName "Norwegian Nynorsk Keyboards"
    description: "Mobile OS keyboards for the Norwegian Nynorsk language from the Divvun group at UiT."
  nb:
    name: "Norwegian Nynorsk tastatur"
    description: "Mobiltastatur for Norwegian Nynorsk fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts:
  - nno-mob
  - nno_Runr-mac
  - nno_Runr-mob
  - nno_Runr-win

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.nno
    icon: images/nno-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.nno
    bundleName: *bundleName
    icon: images/nno-runer.png

  osx:
    <<: *AppleID
    icon: images/nno-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "3B1FD297-4992-4181-B434-4FA6619EE58D"
